src/pages/callback.js

This is a pretty blunt-force fix, but it meets our current use case. We’ll probably want to revisit this as the store evolves.

fix: redirect to dashboard after login

---

package.json
src/components/Modal/Modal.js
src/components/Modal/SizeChartTable.js
src/components/Store/Store.js
src/utils/styles.js
yarn.lock

* using [react-modal](https://github.com/reactjs/react-modal)
* modal close button via react-icons
* using recompose’s „withProps“ to create a styled „td“ with a „colspan“ prop 🙄 (as per https://emotion.sh/docs/with-props)
* modal and „Size Chart“ table are responsive
This solves our basic needs but most likely needs some more work. Not too happy with the „Gender“ table head, but stuck to the example from https://www.apparelnbags.com/next-level/size-chart.htm for now. The table probably also doesn’t need the „Sizes“ table head—feels a bit redundant.
Also currently doesn’t provide any information for clients with JS disabled.
Fixes #41

Add modal with size chart + care instructions

---

README.md

**This PR cannot be merged until gatsbyjs/gatsby#6241 is merged!**
Adds a link to the docs for claiming free swag to the README.
close #56

docs: add link to contributor swag docs

---

src/components/Dashboard/IssueList.js

When looking at good issues to start contributing to Gatsby, I noticed that the label links on the contributor dashboards were broken.
The labels were linking to the GitHub api urls, rather than to GitHub issues.
This PR modifies the IssueList to provide a correctly formatted link to GitHub issues, based on the organisation, repository and label in the provided api url.

Use correct url to link to all the GitHub issues with a certain label

---

package.json
src/components/shared/PrivateRoute.js
src/pages/account.js
src/utils/auth.js
yarn.lock

_Note: the base branch of this is [the reach/router PR](https://github.com/gatsbyjs/store.gatsbyjs.org/pull/111)_
I added the [`noThrow`](https://reach.tech/router/api/Redirect) option to the redirect, it looks like that [thrown error](https://github.com/reach/router/blob/054187e17795c5c2df289109456ce42c48f49343/src/index.js#L411) was being [caught in build-html.js](https://github.com/gatsbyjs/gatsby/blob/26a50baa14845731abf2dbcb688d5d1638d05a39/packages/gatsby/src/commands/build-html.js#L56), which then errors when it tries to handle the unexpected error. This is a workaround rather than a full fix.
Hmm I actually didn't check that the redirect works - I need to call it a night but the site built and the home page fired up.

Router build fix

---

.eslintrc.json
gatsby-node.js
package.json
src/components/Cart/OpenCart.js
src/components/shared/Header/Status.js
src/components/shared/PrivateRoute.js
src/pages/account.js
src/utils/auth.js
yarn.lock

This is updates for the change in Gatsby from using react-router to @reach/router in https://github.com/gatsbyjs/gatsby/pull/6918
Once that's in, I'll update the yarn.lock as well for the store.

Updates for @reach/router change

---

src/components/Cart/LineItem.js
src/components/Cart/ProductImage.js

This adds a `ProductImage` component that takes an image ID and returns a Gatsby Image dressed and ready to head to the dance (i.e., mapped back to a local, responsive image). This resolves/addresses #18.
Cool note: this typically results in the browser selecting the same image that was used for the product preview since it's already loaded, resulting in zero additional requests/data. Win!

Use local product images in cart LineItem (resolves #18)

---

src/components/Cart/OpenCart.js

I followed a common pattern, adding a “Shipping” line item with a rather enthusiastic “FREE” cost detail. I also added “Free shipping worldwide” to the fine print to make it clear to global customers that they weren't being implicitly left out.
Fixes #23.

Clarify shipping costs inside of cart

---

package.json
src/components/Cart/Cart.js
src/context/StoreContext.js
yarn.lock

- Expose a `withStoreContext` HOC
- Convert `Cart` into a class component
- Add [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) to watch for “outside” clicks
- Use existing `toggleCart` and `isCartOpen` state in `StoreContext`
- Don't listen to clicks on “Add to Cart” buttons (causes cart to flash)
- Close cart on “Escape” keyboard event
- Close cart when keyboard navigates to other areas and interacts (e.g., tab to select dropdown and expand select field with keyboard)
Note: If there's a less kludgy, idempotent way to "`closeCart`" with the state being handled the way it is let me know; I'd be happy to revise. 
This resolves #20.

Close cart when click event outside of cart occurs

---

src/components/shared/SiteMetadata.js

It turns out most of the required og and twitter tags where already added in #135.
*Possible Question* - I used one of the existing favicons as the `og:image`. If we can get a better / larger image to use that would be easy to swap out. 
Closes #141

chore: Add additional og and twitter meta tags.

---

src/components/ProductPreview/AddToCart.js
src/components/Store/ProductListings.js

Fix issue #124 
Nice to know you guys have already planned ahead and already styled the button when disabled.
Also, should the button be disabled if all sizes are unavailable? I mean if it didn't users still couldn't add items to the shopping cart.
Sorry for making so many commits.

Handle out of stock

---

src/components/ProductPreview/AddToCart.js

I was looking through the site with an accessibility checker and noticed this label had the wrong for attribute. This should fix a level 'A' problem!
Thanks,
Ross

Add proper ID to label for accessibility

---

src/components/Cart/ProductImage.js

I noticed that flat is not working in Edge. Naturally, because it's not supported yet.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
This is an issue when a user tries to add an item to the cart. 
I played around a little bit with browserlist, but curiously, even explicitly setting Edge won't let it polyfill.
This is a short term fix, ideally, we can get webpack and babel to actually polyfill :|

fix: .flat() not supported in Edge

---

package.json

we should expose a start script that aliases the develop also on this project  #9369 [link](https://github.com/gatsbyjs/gatsby/issues/9369)

add 'start' alias

---

src/utils/auth.js

As the comment states:
> If the user has already logged in, don’t bother fetching again.
However, without an explicit return statement, the function will continue to run and invoke `auth0.client.userInfo()`

prevent fetching auth

---

src/components/ContributorArea/ContentForContributor.js
src/utils/styles.js

Closes #209.
- update styles for used swag code badges
- update messaging
- add badge theming to style utils
Changes left, current right. (Live looks broken because of the Level 2 code change made in Shopify)

used swag code badge style

---

src/components/ContributorArea/ContentForContributor.js

Closes #207.
Where a contributor has earned level 1, but not yet level 2, show a progress bar and messaging toward earning level 2.

level 2 incentive

---

src/components/Cart/Cart.js
src/components/Layout/Layout.js

@jlengstorf found it.
- The shopping cart button will now announce that it's a cart, and number of items.
- Reordered so that navigating with a keyboard, the cart is earlier.

Fix cart button accessibility

---

gatsby-node.js

Products were renamed, including slugs, so this makes sure that no dead links happen.

feat: add redirects

---

src/components/Layout/PageContent.js

Position `Footer` to the bottom of the container, so even when the main content is replaced/hidden by `offline` plugin during page loading the footer does not appear on the top of the page.

fix: flickering footer

---

.env.development
.env.production

- Safari apparently requires trailing slashes or it dumps all hashes. So... we added a trailing slash.
closes #106

fix: no more endless Safari login loops

---

src/components/Layout/Footer.js

It's currently linking to twitter.com/@gatsby 
Should be twitter.com/@gatsbyjs

fix: Update to correct twitter link

---

src/components/ProductListing/ProductListingItem.js

The last one addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/231

fix: product listing swag level 2 flag

---

src/components/shared/Typography.js

Add `width: 100%` to text container

fix: instruction page responsiveness

---

src/components/ContributorArea/OpenBar.js

closes #248: sidebar issue

---

package.json
yarn.lock

I found an issue with gatsby-image on the store site, I created this PR https://github.com/gatsbyjs/gatsby/pull/11303, so the issue has been fixed in the latest version.
close #211

fix: upgrade gatsby-image

---

src/components/ContributorArea/ContentForNotLoggedIn.js
src/components/ContributorArea/OpenIssues.js

The link to searched for open issues was wrong, it didn't find any issue.
The label was `status: help wanted`, the correct label is `help wanted`.
Old link: https://github.com/search?o=desc&q=org%3Agatsbyjs+type%3Aissue+label%3A%22status:%20help%20wanted%22+is%3Aopen&s=updated&type=Issues
New link: https://github.com/search?o=desc&q=org%3Agatsbyjs+type%3Aissue+label%3A%22help%20wanted%22+is%3Aopen&s=updated&type=Issues

Fix link to search for open issues on GitHub

---

package.json

According to my understanding the script `format`: `prettier --write 'src/**/*.js'` doesn't need the apices.
The old syntax generated the following error:
```
> gatsby-store@1.0.0 format C:\Users\[USER]\[PATH]\store.gatsbyjs.org
> prettier --write 'src/**/*.js'
[error] No matching files. Patterns tried: 'src/**/*.js' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gatsby-store@1.0.0 format: `prettier --write 'src/**/*.js'`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gatsby-store@1.0.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! …
```

Fix: npm run format

---

src/components/Layout/Layout.js
src/components/ProductDetails/BackButton.js
src/components/ProductDetails/ProductDetails.js
src/components/ProductPage/ProductForm.js

Closes #238
- Created a new `BackButton` component
- Added function that will either go back to the product page - specified by URL param `?fromProduct` or return to the homepage on the off chance someone stumbles across that page
- Positioned the button to be sticky because due to the #hash deep linking you sometimes would not see the button when you landed on the page

Add Back Button For /product-details page

---

src/components/Layout/Layout.js

Seems like the Layout component has an extra `componentWillUnmount` and `updateViewPortState` by mistake: 
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/4ad1246f2351a9b1aa5d138ceff03e4d3ed8756e/src/components/Layout/Layout.js#L313-L315
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/4ad1246f2351a9b1aa5d138ceff03e4d3ed8756e/src/components/Layout/Layout.js#L345-L347
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/4ad1246f2351a9b1aa5d138ceff03e4d3ed8756e/src/components/Layout/Layout.js#L317-L324
https://github.com/gatsbyjs/store.gatsbyjs.org/blob/4ad1246f2351a9b1aa5d138ceff03e4d3ed8756e/src/components/Layout/Layout.js#L349-L356

Remove method duplication in Layout

---

src/components/Cart/Cart.js

fix: hide free sticker notice when stickers are added to the shopping cart

---

gatsby-browser.js
src/components/Layout/Layout.js
src/utils/auth.js

This is a PR to move the Auth0 tokens from local storage into memory. It also wraps the root element in a `SessionCheck` component to handle silent authentication if the user is already logged in.
This PR Is in DRAFT status because I am unable to debug some of the errors I'm receiving locally. This is likely due to settings in the Auth0 application, e.g. `Allowed Web Origins`, that I don't have access to. If a Gatsby team member could review this code and try to debug it/update the Auth0 application settings, I think we're nearly there with this code!

refactor: move auth from local storage to memory

---

package.json
yarn.lock

I saw some discussion about another option using `lint-staged`. I'm not familiar with that package, but I did get this hook setup using the existing packages (this only adds `husky` to set up the hook).
This change is a simple one and would be one I'd consider until someone has time to integrate `lint-staged`. The process for this solution is...
1) Make code changes
2) Add changed files to the commit
3) Commit code
* Prior to the commit `npm run format` runs then `git add .` is added as well to add any files changed during the format
Typically with my feature branches, it is rare that I'm not committing all files I have changed. However,  if this is common then this option would need a dev to stash their changes first.
Submitting this as a `draft` for @jlengstorf to weigh in on before I …

chore: format code on commit

---

package.json
src/components/Cart/CartList.js
src/components/ContributorArea/CreateAccountForm.js
src/components/Dashboard/IssueList.js
src/components/ProductListing/ProductListingItem.js
src/components/ProductPage/ProductImage.js
src/components/ProductPage/ProductImagesBrowser.js
yarn.lock

Resolves a `:first-child` error.
Resolves a `innerRef` deprecation notice.

fix: remove warnings for :first-child and innerRef

---

src/components/Cart/Cart.js

Close #246. Open for suggestions to a more permanent solution.

Fix: Hide free sticker banner when Gatsby Sticker Pack is in the cart. Close #246

---

src/templates/ProductPageTemplate.js

The website currently uses `siteUrl` (`https://store.gatsbyjs.org`) in the canonical link element of every page, including the product pages. This uses the page's unique pathname instead.

fix: use unique canonical links for product pages

---

package.json

When installing packages via `yarn` cli, they are auto-fixed. Which means that anytime a dev submits a PR with some version upgrade or new package added via `yarn` cli, the package.json file will be reordered.
This causes unnecessary noise in PRs.
The solution here is to fix the ordering. Subsequent PRs should not have this unnecessary change.
Example of the problem:

chore: reorder package.json dependencies

---

README.md

* Fixed grammar issue "only less tasty and **a providing** a bit more coverage" -> "only less tasty and **providing** a bit more coverage"
* Next Gatsby page just redirects to one on the main site so I switched the URL to use that one.
* Changed URLs *slightly* (added www to Shopify because they like that and also made sure that all Gatsby URLs have www at the start)

Update URLs and fix grammar mistake

---

src/components/Cart/CartListItem.js
src/components/ProductPage/ProductForm.js

This PR adds [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) [hint](https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/) to the `Cart list item` and the `Product Form`, this change is aimed to improve user experience in [mobile browsers](https://caniuse.com/#search=inputmode), that way it displays the appropriate keyboard for the form input type being used(which in the particular case is `numeric`).

feat: Add inputmode hint for mobile clients

---

src/components/Layout/Layout.js

Closes the product modal window after navigating "back" in product page
Before:
After:

fix: close product modal after navigating back

---

src/pages/404.js

Updated 404 error page , Put  the whole content in center and added links to Gatsby store page and Github page.
Fixes https://github.com/gatsbyjs/store.gatsbyjs.org/issues/290

404 error page updated

---

src/components/ContributorArea/OpenIssues.js
src/components/Dashboard/OpenIssues.js

Issue:
Even though there is many issues marked as `help wanted`, zero are showing up for a user.
Solution:
Change the label for open issues from `status: help wanted` to `help wanted` so that issues are returned.

fix: open issues looking at wrong label

---

src/components/ProductPage/ProductForm.js

When you go to the product detail from the `size chart` cta, the `back to product` cta redirects to the home instead of back to the product form.
The reason is that the `back to product` button (BackButton.js) looks for `fromProduct` in the query string.
This pr adds that to the originating url and also a hash with `size-chart` (using a similar convention to the `Materials & Fit` and `Care instructions` ctas.

fix back button on product details when navigating from size chart

---

src/components/ContributorArea/ContentForNotContributor.js
src/components/Dashboard/Contributions.js

Change the sidebar support info from Jason's GitHub details for contact to Developer Advocate and Head of Learning @marcysutton GitHub link.

fix: change support name from Jason to Marcy Sutton

---

src/components/ProductListing/ProductListingItem.js

Fixes product links accessibility issues in accessibility audits (links do not have a discernible name).

fix: a11y links do not have discernible names

---

src/components/Layout/Layout.js

Added check for when `shopify_checkout_id` gets set to `null` since localStorage values will be set as Strings.
Closes #312

fix: added null check for local storage (#312)

---

src/pages/404.js

Fix 404 page styling

---

README.md

Since the website domain changed the logo image wasn't loaded in README. Fixed that and added one latest link.

Fix(Docs): Fixed image in README

---

src/components/ProductListing/ProductListingItem.js

The span was showing up as "Code Swag Level1" and "Code Swag Level2".
Noticed this today while redeeming my Level 1 code--which was a surprise to receive. Free swag is such a great way to reward open-source contributions! (Even if it's something small like fixing a typo in the docs.)
Thanks for making Gatsby an awesome tool with an awesome community.

fix: add missing space between "Code Swag Level" and number

---

.github/workflows/rebuild.yml
src/components/ProductListing/ProductListingItem.js
src/components/ProductPage/ProductForm.js

These changes do the following:
- adds a GitHub action to rebuild the site nightly on Gatsby Cloud (we used to have some Zapier thingy hooked into Netlify, but I can't figure out how to get into Zapier and we don't build on Netlify anymore anyway)
- handles missing images better so things don't blow up when a product gets published without one
- tweaks verbiage around variants to say `Size/Color` for new products that have color variations instead of just sizes

chores: add action, verbiage for colors, and handle missing images

---

src/components/ContributorArea/ContentForNotContributor.js
src/components/Dashboard/Contributions.js

I encountered some Links that are only accessible by Gatsby Team Members since normal users won't have access to the internal gatsby org area. 
I removed them so that people like me won't be as confused as I just was.

Remove non-accessible @gatsby/learning links in contributor area

---

package.json
yarn.lock

[See Slack thread for context](https://gatsbyjs.slack.com/archives/C01JTP2K0QZ/p1612364329036000)
We weren't touching the `ShopifyProductImage` nodes on warm builds, causing them to get garbage collected. Version 1.6.1 should fix it.

Version bump to fix inc builds

---

src/components/shared/Buttons.js

Just noticed this while using the store as a reference. Figured I may as well make a PR.
@jlengstorf, kindly review the PR.

fix: Typo in src/components/shared/Buttons
