- src/components/Cart/OpenCart.js
> feat: clarify that all prices are in USD

- src/components/Store/Store.js
- let people know the store isn’t ready yet
- spread a little love
fix #2
> feat: update store copy

- src/components/shared/Header/Profile.js
> feat: link avatar and name to the dashboard

- src/components/ProductPreview/AddToCart.js
- src/components/shared/Layout.js
- require a size selection
- require a quantity greater than 0
fix #28, fix #13
> fix: add size and quantity validation

- src/utils/styles.js
> Darken colors.lilac to meet WCAG 2.0 level AA

- src/components/Dashboard/OpenIssues.js
@m-allanson implemented the new labeling system proposed in https://github.com/gatsbyjs/rfcs/pull/9, so this fix makes sure we still see issues with help wanted.
> fix: update issue labels

- README.md
Listed out the questions we're getting for items in the store.
> Added FAQ section to the README

- src/components/Modal/Modal.js
- src/components/Modal/SizeChartTable.js
- src/components/ProductPreview/AddToCart.js
- src/components/ProductPreview/ProductPreview.js
I added a few changes that I felt were useful/important:
- Automatically convert between inches and centimeters in the size chart
- Don't show a size selector for socks and stickers
- Fix alignment of [Add to Cart] buttons
Cheers!
> UX Enhancements 🎉

- gatsby-config.js
- src/components/shared/Layout.js
- src/components/shared/SiteMetadata.js
> Improve site metadata

- .circleci/config.yml
- package.json
I can also set up the scaffolding for the e2e tests, but obviously we don't have those yet. Let me know if you have any feedback/requests for changes 👍
> feat(ci): add circleci integration and scaffolding for test/lint

- gatsby-config.js
- package.json
- src/components/Cart/ItemList.js
- src/components/Cart/LineItem.js
- src/components/Cart/OpenCart.js
- src/components/shared/Layout.js
- src/context/StoreContext.js
- yarn.lock
ref #118 
Hi 👋 !
Will attempt to add this functionality.
Can you tell me if I'm going in the right direction please?
If I (roughly) am, how should I implement the function that changing the quantity calls?
> feat: change counts in cart

- src/pages/callback.js
Currently, the auth callback page just displays some text in the default system font, which I thought was kind of ugly, so I decided to make it look a bit nicer 😄!
Screenshot:
> Make auth callback page nicer

- src/components/Dashboard/OpenIssues.js
closes https://github.com/gatsbyjs/store.gatsbyjs.org/issues/155
> filter out claimed issues from github response

- README.md
Hey,
This is just a really simple change that makes sure that they know the email address, especially as each other section that refers to sending emails has the email address 🙂
> Adding email address to the international shipments section

- gatsby-config.js
- package.json
- src/components/shared/SiteMetadata.js
- yarn.lock
- Add offline support
- Add `preconnect` links for the Shopify and Gatsby APIs
> feat: improvements to make Lighthouse happy

- src/components/ProductDetails/ProductDetails.js
This adds care instructions for the new hoodies and water bottles.
Also there were apparently linter problems. 😕
> feat: update care instructions

- .env.development
- .env.production
- gatsby-config.js
- src/context/StoreContext.js
Moving the Shopify access token to .env file and use this in both places where we need the access token.
Closes #198
> Move Shopify tokens to .env file

- gatsby-config.js
- package.json
- yarn.lock
- update to the Gatsby-maintained Shopify plugin (see https://github.com/gatsbyjs/gatsby/pull/10955)
- update the Shopify Buy SDK
> chore: use official Shopify plugin

- src/components/ProductPage/CommunityCaption.js
- src/templates/ProductPageTemplate.js
- use product info and image for SEO tags on product pages
- fix lorem ipsum text in captions
> fix: product page SEO and captions

- src/components/Layout/Layout.js
- src/components/ProductPage/ProductImagesMobile.js
Addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/226/files
Fix '0' flickering during page loading
> fix: pdate photos info and remove flickering '0'

- src/components/ProductListing/ProductListingItem.js
Update conditional code to work with the new string of swag code level 2
> fix: product listing swag level 2 flag

- src/components/ProductListing/ProductListingItem.js
It's addition to https://github.com/gatsbyjs/store.gatsbyjs.org/pull/231
> fix: product listing swag level 2 flag - addition

- src/components/ContributorArea/ContentForContributorWithNoAccount.js
- src/components/ContributorArea/ContentForNotContributor.js
- src/components/ContributorArea/CreateAccountForm.js
Before, only the label clicks worked. Also removed some unused imports.
closes #227
> fix: enable clicking on checkbox

- src/components/Cart/Cart.js
- src/components/Cart/CartListItem.js
> closes #241: Addressed the behavior of Cart getting disabled on removing an item

- src/components/ContributorArea/ContentForContributor.js
removed duplicate selector `::-webkit-progress-value`
> fix(ContentForContributor):Remove duplicate selector

- src/components/ProductDetails/SizeChartTable.js
This PR is in reference to the issue #256
> size chart typo fixed

- src/components/Cart/Cart.js
Instead of creating a variable by looping over the full array we will use the native `Array​.prototype​.some()` functionality. More documentation of this functionality can be found on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
> refactor: use native Array.prototype.some() functionality

- src/components/Cart/CartListItem.js
- src/components/Cart/CartThumbnail.js
Just noticed this one while using the store as a reference. Figured I may aswell make a PR
> Fix typo with thumbnail spelling

- src/components/ProductDetails/SizeChartTable.js
- yarn.lock
Updated the size chart to include sizes for the various pants.
> Add pajama pants sizing

- src/components/ContributorArea/ContentForContributor.js
- yarn.lock
After looking through issues, i noticed there was a stale one for a button to press to copy the code to the clipboard.
This works by passing it down to a function, so if we add level 3 onwards it'll work also.
> Add ability to copy the code with a button

- src/components/Layout/Footer.js
Adding link to faqs on the footer so that there is more info when people get stuck.
> Adding link to faqs

- src/components/Cart/ShippingInfo.js
Adding some useful info for people placing orders from outside the US.  Hopefully, this makes it clearer about custom charges that might be incurred.
> Adding message for international orders about taxes

- src/components/ContributorArea/ContributorArea.js
:writing_hand: **Fix typo across store.gatsbyjs.org repo**
**File that have typo**
```
store.gatsbyjs.org/src/components/ContributorArea/ContributorArea.js:100:11: "inital" is a misspelling of "initial"
```
**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart:
> Fix typo across store.gatsbyjs.org repo

- README.md
Updating the README with something we can point to for the community in the event they get the wrong t-shirt size.
> Update README with info about wrong t-shirt sizes

- src/components/Layout/Layout.js
I opened an Issue: #398 and I solve it by giving a background to the body of the website.
> fix: set body background to white
